on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
      - run: node -e "console.debug(os.platform())"
      - run: node -e "console.debug(os.arch())"
